version: "3.9"

services:
  backend:
    build: ./fastapi_backend
    container_name: shopping_list_api
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_backend:/app
    restart: unless-stopped

